version: 2.1

orbs:
  maven: circleci/maven@0.0.12
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    resource_class: small
    steps:
      - checkout
      - run: sudo apt update && sudo apt install openjdk-11-jre
      - run: sudo apt install maven -y && mvn -version
      - run: sudo mvn install && ls -l target

workflows:
  maven_test:
    jobs:
      - build
      #- maven/test
