version: 2.1

orbs:
  maven: circleci/maven@0.0.12
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    resource_class: small
    steps:
      - checkout
      - run: sudo apt install maven -y && mvn -version
      - run: sudo mvn install && ls -l target

workflows:
  maven_test:
    jobs:
      - maven/test
